export enum EmptyStates {
  NO_DATA,
  NO_RESULTS_SEARCH,
  SELECT_DRIVER_FOR_SEARCH,
  GENERAL,
  ERROR,
  DASHBOARD_INCOME,
  DASHBOARD_PRODUCTS,
  MAP,
  SELECT_COURIER_FOR_SEARCH,
  NO_DATA_CUSTOM,
  NO_BONUS_DATA,
  UNSUPPORTED_DATA,
}
