export enum Colors {
  WHITE = 'White',
  BLACK = 'Black',
  RED = 'Red',
  GREEN = 'Green',
  BROWN = 'Brown',
  BEIGE = 'Beige',
  PURPLE = 'Purple',
  ORANGE = 'Orange',
  OLIVE = 'Olive',
  NAVY = 'Navy',
  SILVER = 'Silver',
  GRAY = 'Gray',
  YELLOW = 'Yellow',
  TEAL = 'Teal',
  FUCHSIA = 'Fuchsia',
  LIME = 'Lime',
  AQUA = 'Aqua',
  MAROON = 'Maroon',
  BLUE = 'Blue',
}
