export enum ProductType {
  ALL = 'all',
  MINIVAN = 'minivan',
  GREEN = 'green',
  POOL = 'pool',
  ECONOM = 'econom',
  PREMIUM = 'premium',
  STANDARD = 'standard',
  WAGON = 'wagon',
  DELIVERY = 'delivery',
  BUSINESS = 'business',
  COVID_PROTECTED = 'covidProtected',
  DRIVER = 'driver',
  EVACUATION = 'evacuation',
  EVACUATION_MD = 'evacuationmd',
  KIDS = 'kids',
  VAN = 'van',
  SHARE = 'share',
  TAXI = 'taxi',
  VOLUNTEER = 'volunteer',
  COMFORT_PLUS = 'comfortplus',
}
