export enum CorePaths {
  EMPTY = '',
  FULL = 'full',
  UNKNOWN = '**',
  GENERAL = 'general',
  WORKSPACE = 'workspace',
  AUTH = 'auth',
  ACCOUNT = 'account',
  DRIVERS = 'drivers',
  VEHICLES = 'vehicles',
  ORDERS = 'orders',
  FINANCE = 'finance',
  FEEDBACKS = 'feedbacks',
  CONTACTS = 'contacts',
  LIVE_MAP = 'live-map',
  FLEET_FORBIDDEN = 'forbidden',
  COURIERS = 'couriers',
  COURIERS_MAP = 'couriers/live-map',
  COURIERS_ORDERS = 'couriers/orders',
  COURIERS_FINANCE = 'couriers/finance',
  COURIERS_FEEDBACKS = 'couriers/feedbacks',
  FLEET_PROFILE = 'fleet-profile',
  BONUSES = 'bonuses',
  SUCCESS = 'success',
}
